### ISSUE TITLE
[Answered] MRPC Reproducibility

### ISSUE THREAD

**Issue by YaNjIeE** [JetRunner/BERT-of-Theseus#1]
Hi, I read this paper and the idea is interesting.

However, after I run your code, I cannot achieve the performance in the paper.
For instance, the MRPC dataset is used to finetuning the teacher model, then the model is loaded and used to distill the dark knowledge to the student model. But the final performance of student on the MRPC dataset is 85.2, which is much lower than the result in the paper, i.e., 89.0.

I do not know why that happen, would you please help me out?

Best.

**Comment by JetRunner** [comment]
Thanks for your interest in our paper.

I wonder what hyper-parameters did you use for your experiments? Please confirm two things:

1. Your predecessor model can achieve comparable performance as our predecessor model (BERT-base in Table 2). 

2. You follow the exact hyper-parameters (grid-searched in our paper). **DO NOT** use the example hyper-parameters in our Github README. They are just there for example. 

In our experiments, we never saw a successor on MRPC which performs lower than `87.5`.

Please do try multiple sets of hyper-parameters and we are happy to answer your further questions.

**Comment by YaNjIeE** [comment]
Thanks, I will run this code with grid search.

Best.

**Comment by YaNjIeE** [comment]
Hi, one more thing to confirm: after the compression processing, is there a processing for fine-tuning the student model? I mean, in the compression processing, actually there is a fine-tuning processing for student model, and do we need another fine-tuning for it?

**Comment by JetRunner** [comment]
> Hi, one more thing to confirm: after the compression processing, is there a processing for fine-tuning the student model? I mean, in the compression processing, actually there is a fine-tuning processing for student model, and do we need another fine-tuning for it?

No, no need for that.

**Comment by JetRunner** [comment]
Closing it for being inactive. Pls. reopen it if you have further questions.
