### ISSUE TITLE
how to draw the cover picture?

### ISSUE THREAD

**Issue by MrRace** [JetRunner/BERT-of-Theseus#11]
how to draw the cover picture? excuse me, for the  serious curious about your logo of BERT-of-Theseus.  With some advanced technology or just use Photoshop?
![image](https://user-images.githubusercontent.com/10300313/92064569-4d0e8880-edd0-11ea-9e9c-a890fef9bfc5.png)

**Comment by JetRunner** [comment]
LoL just Photoshop with some filters. No magic.
