### ISSUE TITLE
[Answered] Does Theseus support pruning width of network?

### ISSUE THREAD

**Issue by jiezhangGt** [JetRunner/BERT-of-Theseus#2]
Hi, thanks for your share of Theseus.  To my understanding, Theseus can support prune depth of the network， I wonder if it can also  support prune width of the network?

**Comment by JetRunner** [comment]
Thanks for your interest in our work.

Well, we've discussed this in the last section of our paper. 

By now, we can only reduce the depth of a model but we can also use a totally different network as a substitution (e.g., Reformer).

We also proposed to use an MLP to map between different hidden sizes, like the one in TinyBERT. We haven't tried that so far but we encourage the community for further improvement.

**Comment by JetRunner** [comment]
Closing it for being inactive. Pls. reopen it if you have further questions.
