### ISSUE TITLE
Why the model of pytorch_model.bin is also 579.3MB?

### ISSUE THREAD

**Issue by janyChan** [JetRunner/BERT-of-Theseus#4]
Why the model of pytorch_model.bin is as big as 579.3MB?

**Comment by JetRunner** [comment]
Good question. For the convenience of experiments, we kept the original layers in the saved model. If you want to get rid of them, simply add this line before saving the model:
```python
del model.layer
```
It won’t affect the inference since the inference only uses `model.scc_layer`. Hope it helps.

**Comment by JetRunner** [comment]
Also FYI, we’ll add a script to convert a Bert-of-Theseus model to a normal huggingface BERT model later.

**Comment by JetRunner** [comment]
Closing it for being inactive. Please reopen it if you have any further question.
