### ISSUE TITLE
Can I easily changed the number of hidden layers for scc_layer?

### ISSUE THREAD

**Issue by ArranGrimm** [JetRunner/BERT-of-Theseus#6]
First, thank you for the amazing work.
     I have already use this method to train a small Bert(6 hidden layers) from the Bert-base(12 hidden layers), and in my own dataset the **inference speed almost double** but the **accuracy goes down from 84.5% to 82.8%**. So I'm wondering if I can use Roberta-large(24 hidden layers) as the predecessor model and set the number of hidden layers for scc_layer to 8?

Because in **modeling_bert_of_theseus.py** I found such code lines:

> def __init__(self, config, **scc_n_layer=6**):

        super(BertEncoder, self).__init__()
        self.prd_n_layer = config.num_hidden_layers
        self.scc_n_layer = scc_n_layer
        assert self.prd_n_layer % self.scc_n_layer == 0

**Comment by JetRunner** [comment]
Hi Jaeker,

Thanks for your interest in our work.

I would say 84.5 to 82.8 is fairly satisfying given the speed doubles. Also, you can change scc_n_layer as you wish. Alas, currently we only support BERT so you can’t use RoBERTa at this moment. Or you can modify the RoBERTa from Hugging Face transformers and use our code as a reference. If you don’t want to write codes, you can try BERT large.

Thanks again for your good words.

**Comment by ArranGrimm** [comment]
Thank you for the reply!
Finally I get the RoBERTa worked with Theseus.
