### ISSUE TITLE
The performance of DistilBERT

### ISSUE THREAD

**Issue by forjiuzhou** [JetRunner/BERT-of-Theseus#8]
I notice that the performance you report here differs significantly with distilbert in their paper, why?
![image](https://user-images.githubusercontent.com/8179405/87910951-6d42ec00-ca9d-11ea-88b4-321cd418c73c.png)

**Comment by JetRunner** [comment]
When we wrote our paper, the latest version of DistilBERT paper was: https://arxiv.org/pdf/1910.01108v3.pdf
![image](https://user-images.githubusercontent.com/22514219/87911388-1db0f000-ca9e-11ea-9da5-244578545d84.png)
We derived the results from this version.

Obviously, the authors of DistilBERT updated their results afterward.
